## File name: config.py
## Description: Central place for constants

SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800
SCREEN_COLOR = (0, 0, 0) # Black
FPS = 60

FRIEND_X_SPEED = 3
FRIEND_Y_SPEED = 3
FRIEND_RADIUS = 10
FRIEND_COLOR = (0, 255, 0) # Green

ENEMY_X_SPEED = 1
ENEMY_Y_SPEED = 1
ENEMY_RADIUS = 10
ENEMY_COLOR= (255, 0, 0) # Red
NUM_ENEMIES = 3

THREAT_SCORE_THRESHOLD = 10
MIN_SPEED = 0.1
DISTANCE_WEIGHT = 1000