## File name: config.py
## Description: Central place for constants

SCREEN_WIDTH = 600
SCREEN_HEIGHT = 600
SCREEN_COLOR = (0, 0, 0) # Black
FPS = 60

FRIEND_X_SPEED = 3
FRIEND_Y_SPEED = 3
FRIEND_RADIUS = 10
FRIEND_COLOR = (0, 255, 0) # Green

ENEMY_X_SPEED = 2
ENEMY_Y_SPEED = 2
ENEMY_RADIUS = 10
ENEMY_COLOR= (255, 0, 0) # Red

DETECTION_RADIUS = 50
MIN_SPEED = 0.1